In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

print(arr.shape)
print(arr_2d.shape)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
(5,)
(2, 3)


In [7]:
print(arr[2])
print(arr_2d[1, 2])
print(arr[1:4])
print(arr_2d[:,1])

3
6
[2 3 4]
[2 5]


In [9]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d = np.reshape(arr_2d,(1, 6))

print(arr_2d)

[[1 2 3 4 5 6]]


In [2]:
arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(arr + arr2)
print(arr * 2)
print(arr - arr2)

[ 7  9 11 13 15]
[ 2  4  6  8 10]
[-5 -5 -5 -5 -5]


In [11]:
arr = np.array([2,1,5,6])

print(np.mean(arr))
print(np.sum(arr))
print(np.std(arr))
print(np.min(arr))
print(np.max(arr))
print(np.sort(arr))

3.5
14
2.0615528128088303
1
6
[1 2 5 6]


In [14]:
arr = np.array([1,2,3]) # 5 + 1 => 6, 5 + 2 => 7, 5 + 3 => 8
result = arr + 5
print(result)

[6 7 8]


In [15]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_1d = np.array([1,2,3])
result = arr_2d + arr_1d
print(result)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [16]:
import pandas as pd

df = pd.read_csv("sales_data_100.csv")
print(df)

    OrderID     Product    Category  Quantity  Price   OrderDate   Region
0      1001      Tablet          IT         1   7000  2024-02-07     East
1      1002     Printer          IT         1   6000  2024-02-23  Central
2      1003    Keyboard          IT         4    500  2024-02-04  Central
3      1004  Whiteboard   Furniture         6   1800  2024-01-28    South
4      1005      Tablet          IT         4   7000  2024-01-15     East
..      ...         ...         ...       ...    ...         ...      ...
95     1096  Whiteboard   Furniture        10   1800  2024-02-18    South
96     1097       Chair   Furniture         5   2000  2024-02-14     East
97     1098    Keyboard          IT         1    500  2024-02-01  Central
98     1099         Pen  Stationery         2     10  2024-01-06     East
99     1100    Notebook  Stationery        10     30  2024-02-25    North

[100 rows x 7 columns]


In [17]:
print(df.head())

   OrderID     Product   Category  Quantity  Price   OrderDate   Region
0     1001      Tablet         IT         1   7000  2024-02-07     East
1     1002     Printer         IT         1   6000  2024-02-23  Central
2     1003    Keyboard         IT         4    500  2024-02-04  Central
3     1004  Whiteboard  Furniture         6   1800  2024-01-28    South
4     1005      Tablet         IT         4   7000  2024-01-15     East


In [18]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   OrderID    100 non-null    int64 
 1   Product    100 non-null    object
 2   Category   100 non-null    object
 3   Quantity   100 non-null    int64 
 4   Price      100 non-null    int64 
 5   OrderDate  100 non-null    object
 6   Region     100 non-null    object
dtypes: int64(3), object(4)
memory usage: 5.6+ KB
None


In [19]:
print(df.describe())

           OrderID    Quantity         Price
count   100.000000  100.000000    100.000000
mean   1050.500000    5.610000   3196.600000
std      29.011492    3.051395   4640.938128
min    1001.000000    1.000000      3.000000
25%    1025.750000    3.000000     30.000000
50%    1050.500000    5.000000   2000.000000
75%    1075.250000    8.250000   6000.000000
max    1100.000000   10.000000  25000.000000


In [20]:
print(df['Category'])

0             IT
1             IT
2             IT
3      Furniture
4             IT
         ...    
95     Furniture
96     Furniture
97            IT
98    Stationery
99    Stationery
Name: Category, Length: 100, dtype: object


In [21]:
print(df[['Product', 'Price']])

       Product  Price
0       Tablet   7000
1      Printer   6000
2     Keyboard    500
3   Whiteboard   1800
4       Tablet   7000
..         ...    ...
95  Whiteboard   1800
96       Chair   2000
97    Keyboard    500
98         Pen     10
99    Notebook     30

[100 rows x 2 columns]


In [22]:
df.iloc[2]

OrderID            1003
Product        Keyboard
Category             IT
Quantity              4
Price               500
OrderDate    2024-02-04
Region          Central
Name: 2, dtype: object

In [23]:
df.iloc[2:4]

OrderID     Product   Category  Quantity  Price   OrderDate   Region
2     1003    Keyboard         IT         4    500  2024-02-04  Central
3     1004  Whiteboard  Furniture         6   1800  2024-01-28    South

In [24]:
df.loc[df['Region'] == 'Central']

OrderID     Product    Category  Quantity  Price   OrderDate   Region
1      1002     Printer          IT         1   6000  2024-02-23  Central
2      1003    Keyboard          IT         4    500  2024-02-04  Central
8      1009      Laptop          IT         2  25000  2024-01-20  Central
13     1014      Tablet          IT         2   7000  2024-01-26  Central
21     1022         Pen  Stationery         3     10  2024-01-31  Central
25     1026         Pen  Stationery         8     10  2024-01-01  Central
27     1028    Notebook  Stationery         9     30  2024-01-26  Central
28     1029       Chair   Furniture         6   2000  2024-01-15  Central
33     1034  Whiteboard   Furniture        10   1800  2024-01-22  Central
34     1035      Tablet          IT         2   7000  2024-01-27  Central
37     1038       Mouse          IT         4    150  2024-01-22  Central
41     1042      Tablet          IT         4   7000  2024-01-02  Central
48     1049        Desk   Furniture         2   3000  2024-02-02  Central
49     1050        Desk   Furniture         5   3000  2024-01-11  Central
57     1058       Mouse          IT         3    150  2024-01-25  Central
59     1060      Pencil  Stationery         9      5  2024-02-17  Central
64     1065       Chair   Furniture         8   2000  2024-02-20  Central
68     1069        Desk   Furniture        10   3000  2024-01-03  Central
71     1072      Tablet          IT         9   7000  2024-01-23  Central
77     1078      Pencil  Stationery        10      5  2024-01-21  Central
93     1094       Mouse          IT         2    150  2024-02-08  Central
97     1098    Keyboard          IT         1    500  2024-02-01  Central

In [26]:
df.loc[(df['Category'] == 'IT') & (df['Quantity'] > 100)]

Empty DataFrame
Columns: [OrderID, Product, Category, Quantity, Price, OrderDate, Region]
Index: []